# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 491)
        MainWindow.setStyleSheet("background-color: #e9e6f2;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: transparent;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setStyleSheet("background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ece9f7,\n"
"        stop:1 #ddd8ee\n"
"    );\n"
"border-radius: 24px;")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.HeaderFrame = QtWidgets.QFrame(self.mainFrame)
        self.HeaderFrame.setGeometry(QtCore.QRect(0, 0, 881, 31))
        self.HeaderFrame.setStyleSheet("background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #8f97c8,\n"
"        stop:1 #b8bbe3\n"
"    );\n"
"border-top-left-radius: 22px;\n"
"border-top-right-radius: 22px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;")
        self.HeaderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HeaderFrame.setObjectName("HeaderFrame")
        self.softwareNameLabel = QtWidgets.QLabel(self.HeaderFrame)
        self.softwareNameLabel.setGeometry(QtCore.QRect(66, 3, 201, 21))
        self.softwareNameLabel.setStyleSheet("    background: transparent;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"    border: none;")
        self.softwareNameLabel.setObjectName("softwareNameLabel")
        self.logoLabel = QtWidgets.QLabel(self.HeaderFrame)
        self.logoLabel.setGeometry(QtCore.QRect(30, 0, 31, 31))
        self.logoLabel.setStyleSheet("    background: transparent;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    border: none;")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.closeButton = QtWidgets.QPushButton(self.HeaderFrame)
        self.closeButton.setGeometry(QtCore.QRect(824, 0, 51, 31))
        self.closeButton.setStyleSheet("QPushButton#minimizeButton,\n"
"QPushButton#closeButton {\n"
"    background-color: rgba(255, 255, 255, 0.10);\n"
"    color: white;\n"
"    border: 1px solid rgba(255, 255, 255, 0.35);\n"
"    border-radius: 8px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton#minimizeButton:hover,\n"
"QPushButton#closeButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.20);\n"
"}\n"
"\n"
"QPushButton#minimizeButton:pressed,\n"
"QPushButton#closeButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.28);\n"
"}")
        self.closeButton.setObjectName("closeButton")
        self.minimizeButton = QtWidgets.QPushButton(self.HeaderFrame)
        self.minimizeButton.setGeometry(QtCore.QRect(770, 0, 51, 31))
        self.minimizeButton.setStyleSheet("QPushButton#minimizeButton,\n"
"QPushButton#pushButton {\n"
"    background-color: rgba(255, 255, 255, 0.10);\n"
"    color: white;\n"
"    border: 1px solid rgba(255, 255, 255, 0.35);\n"
"    border-radius: 8px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton#minimizeButton:hover,\n"
"QPushButton#pushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.20);\n"
"}\n"
"\n"
"QPushButton#minimizeButton:pressed,\n"
"QPushButton#pushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.28);\n"
"}")
        self.minimizeButton.setObjectName("minimizeButton")
        self.bodyFrame = QtWidgets.QFrame(self.mainFrame)
        self.bodyFrame.setGeometry(QtCore.QRect(0, 40, 881, 421))
        self.bodyFrame.setStyleSheet("    background-color: rgba(255, 255, 255, 0.18);\n"
"    border-bottom-left-radius: 22px;\n"
"    border-bottom-right-radius: 22px;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;")
        self.bodyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bodyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bodyFrame.setObjectName("bodyFrame")
        self.mainBoxcontainer = QtWidgets.QFrame(self.bodyFrame)
        self.mainBoxcontainer.setGeometry(QtCore.QRect(10, 10, 861, 371))
        self.mainBoxcontainer.setStyleSheet("    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(255,255,255,0.34),\n"
"        stop:1 rgba(255,255,255,0.20)\n"
"    );\n"
"    border: 1px dashed #d3cede;\n"
"    border-radius: 22px;")
        self.mainBoxcontainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBoxcontainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBoxcontainer.setObjectName("mainBoxcontainer")
        self.dragAnddropicon = QtWidgets.QLabel(self.mainBoxcontainer)
        self.dragAnddropicon.setGeometry(QtCore.QRect(90, 150, 681, 71))
        self.dragAnddropicon.setStyleSheet("    background: transparent;\n"
"    color: #8f93b7;\n"
"    font-size: 54px;\n"
"    font-weight: 400;\n"
"    border: none;")
        self.dragAnddropicon.setAlignment(QtCore.Qt.AlignCenter)
        self.dragAnddropicon.setObjectName("dragAnddropicon")
        self.uploadImagebutton = QtWidgets.QPushButton(self.mainBoxcontainer)
        self.uploadImagebutton.setGeometry(QtCore.QRect(320, 240, 181, 41))
        self.uploadImagebutton.setStyleSheet("QPushButton#uploadImagebutton {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #8f9ad8,\n"
"        stop:1 #b4b8e9\n"
"    );\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 18px;\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"    padding: 10px 22px;\n"
"}\n"
"\n"
"QPushButton#uploadImagebutton:hover {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #8692d2,\n"
"        stop:1 #aeb3e4\n"
"    );\n"
"}\n"
"\n"
"QPushButton#uploadImagebutton:pressed {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #7986c8,\n"
"        stop:1 #a0a8dc\n"
"    );\n"
"}")
        self.uploadImagebutton.setObjectName("uploadImagebutton")
        self.uploadIconlabel = QtWidgets.QLabel(self.mainBoxcontainer)
        self.uploadIconlabel.setGeometry(QtCore.QRect(360, 70, 121, 61))
        self.uploadIconlabel.setStyleSheet("    background: transparent;\n"
"    color: #74758a;\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"    border: none;")
        self.uploadIconlabel.setText("")
        self.uploadIconlabel.setObjectName("uploadIconlabel")
        self.frame = QtWidgets.QFrame(self.bodyFrame)
        self.frame.setGeometry(QtCore.QRect(10, 10, 861, 401))
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 0.15);\n"
"border-top: 0px solid rgba(210,205,225,0.8);\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 370, 811, 21))
        self.label_3.setStyleSheet("    background: transparent;\n"
"    color: #7c7d92;\n"
"    font-size: 13px;\n"
"    font-weight: 400;\n"
"    border: none;\n"
"    padding-left: 12px;\n"
"    padding-right: 12px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame.raise_()
        self.mainBoxcontainer.raise_()
        self.gridLayout.addWidget(self.mainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.softwareNameLabel.setText(_translate("MainWindow", "Teardown AI Software"))
        self.closeButton.setText(_translate("MainWindow", "X"))
        self.minimizeButton.setText(_translate("MainWindow", "-"))
        self.dragAnddropicon.setText(_translate("MainWindow", "Tap or drag IC image here"))
        self.uploadImagebutton.setText(_translate("MainWindow", "Upload an image"))
        self.label_3.setText(_translate("MainWindow", "Upload an image of an IC and the software will segment different blocks from the teardown IC for analysis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
