# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segmented_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(627, 681)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #ebe8f3;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    background: transparent;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setStyleSheet("QFrame#mainFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #f3f1f8,\n"
"        stop:1 #ddd8ee\n"
"    );\n"
"    border: 1px solid rgba(255,255,255,0.65);\n"
"    border-radius: 24px;\n"
"}")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.HeaderFrame = QtWidgets.QFrame(self.mainFrame)
        self.HeaderFrame.setGeometry(QtCore.QRect(30, 0, 561, 31))
        self.HeaderFrame.setStyleSheet("QFrame#HeaderFrame {\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.HeaderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HeaderFrame.setObjectName("HeaderFrame")
        self.softwareNameLabel = QtWidgets.QLabel(self.HeaderFrame)
        self.softwareNameLabel.setGeometry(QtCore.QRect(0, 0, 221, 31))
        self.softwareNameLabel.setStyleSheet("QLabel#softwareNameLabel {\n"
"    background: transparent;\n"
"    color: #5f6172;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    border: none;\n"
"    padding-left: 6px;\n"
"}")
        self.softwareNameLabel.setObjectName("softwareNameLabel")
        self.Image_showing_frame = QtWidgets.QFrame(self.mainFrame)
        self.Image_showing_frame.setGeometry(QtCore.QRect(-10, 40, 621, 281))
        self.Image_showing_frame.setStyleSheet("QFrame#Image_showing_frame {\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.Image_showing_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Image_showing_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Image_showing_frame.setObjectName("Image_showing_frame")
        self.originalImageframe = QtWidgets.QFrame(self.Image_showing_frame)
        self.originalImageframe.setGeometry(QtCore.QRect(20, 10, 281, 231))
        self.originalImageframe.setStyleSheet("QFrame#originalImageframe, QFrame#segmentedImageframe {\n"
"    background: rgba(124, 120, 154, 0.22);\n"
"    border: 1px solid rgba(255,255,255,0.55);\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QLabel#originalImagelabel, QLabel#segmentedImagelabel {\n"
"    background: transparent;\n"
"    color: #676779;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"    border: none;\n"
"}")
        self.originalImageframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.originalImageframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.originalImageframe.setObjectName("originalImageframe")
        self.segmentedImageframe = QtWidgets.QFrame(self.Image_showing_frame)
        self.segmentedImageframe.setGeometry(QtCore.QRect(330, 10, 281, 231))
        self.segmentedImageframe.setStyleSheet("QFrame#originalImageframe, QFrame#segmentedImageframe {\n"
"    background: rgba(124, 120, 154, 0.22);\n"
"    border: 1px solid rgba(255,255,255,0.55);\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QLabel#originalImagelabel, QLabel#segmentedImagelabel {\n"
"    background: transparent;\n"
"    color: #676779;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"    border: none;\n"
"}")
        self.segmentedImageframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.segmentedImageframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.segmentedImageframe.setObjectName("segmentedImageframe")
        self.originalImagelabel = QtWidgets.QLabel(self.Image_showing_frame)
        self.originalImagelabel.setGeometry(QtCore.QRect(50, 230, 211, 41))
        self.originalImagelabel.setStyleSheet("QLabel {\n"
"    color: #5d5e70;\n"
"    background: transparent;\n"
"    border: none;\n"
"    font: bold\n"
"}")
        self.originalImagelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.originalImagelabel.setObjectName("originalImagelabel")
        self.segmentedImagelabel = QtWidgets.QLabel(self.Image_showing_frame)
        self.segmentedImagelabel.setGeometry(QtCore.QRect(360, 230, 211, 41))
        self.segmentedImagelabel.setStyleSheet("QLabel {\n"
"    color: #5d5e70;\n"
"    background: transparent;\n"
"    border: none;\n"
"    font: bold\n"
"}")
        self.segmentedImagelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.segmentedImagelabel.setObjectName("segmentedImagelabel")
        self.showDetailsframe = QtWidgets.QFrame(self.mainFrame)
        self.showDetailsframe.setGeometry(QtCore.QRect(10, 330, 591, 271))
        self.showDetailsframe.setStyleSheet("QFrame#showDetailsframe {\n"
"    background: rgba(255,255,255,0.30);\n"
"    border: 1px solid rgba(255,255,255,0.55);\n"
"    border-radius: 16px;\n"
"}")
        self.showDetailsframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.showDetailsframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.showDetailsframe.setObjectName("showDetailsframe")
        self.closePushbutton = QtWidgets.QPushButton(self.mainFrame)
        self.closePushbutton.setGeometry(QtCore.QRect(10, 610, 591, 41))
        self.closePushbutton.setStyleSheet("QPushButton#closePushbutton {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #a9addf,\n"
"        stop:1 #8e93d5\n"
"    );\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton#closePushbutton:hover {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #b3b7e8,\n"
"        stop:1 #999edf\n"
"    );\n"
"}\n"
"\n"
"QPushButton#closePushbutton:pressed {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #8f94d0,\n"
"        stop:1 #7d82c7\n"
"    );\n"
"}\n"
"")
        self.closePushbutton.setObjectName("closePushbutton")
        self.gridLayout.addWidget(self.mainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.softwareNameLabel.setText(_translate("MainWindow", "IC Teardown Analysis"))
        self.originalImagelabel.setText(_translate("MainWindow", "Original Image"))
        self.segmentedImagelabel.setText(_translate("MainWindow", "Segmented Image"))
        self.closePushbutton.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
