# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\project_Files\landing_Page\UI\dot_UI_files\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(991, 767)
        MainWindow.setMinimumSize(QtCore.QSize(700, 740))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #e9e8f4;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    background: transparent;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setStyleSheet("QFrame#mainFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #f1eff9,\n"
"        stop:0.45 #eceaf7,\n"
"        stop:1 #dfe7f8\n"
"    );\n"
"    border: 1px solid rgba(255,255,255,0.50);\n"
"    border-radius: 26px;\n"
"}")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.HeaderFrame = QtWidgets.QFrame(self.mainFrame)
        self.HeaderFrame.setGeometry(QtCore.QRect(0, 0, 971, 45))
        self.HeaderFrame.setStyleSheet("QFrame#HeaderFrame {\n"
"    background: qlineargradient(x1:0,y1:0,x2:1,y2:0, stop:0 #8d96cb, stop:1 #b6bae6);\n"
"    border-top-left-radius: 22px;\n"
"    border-top-right-radius: 22px;\n"
"}")
        self.HeaderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HeaderFrame.setObjectName("HeaderFrame")
        self.logoPushbutton = QtWidgets.QPushButton(self.HeaderFrame)
        self.logoPushbutton.setGeometry(QtCore.QRect(22, -2, 40, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoPushbutton.sizePolicy().hasHeightForWidth())
        self.logoPushbutton.setSizePolicy(sizePolicy)
        self.logoPushbutton.setStyleSheet("QPushButton#logoPushbutton { background: transparent; color: white; border: none; font-size: 50px; font-weight: 700; }")
        self.logoPushbutton.setText("")
        self.logoPushbutton.setObjectName("logoPushbutton")
        self.softwareNameLabel = QtWidgets.QLabel(self.HeaderFrame)
        self.softwareNameLabel.setGeometry(QtCore.QRect(68, 10, 320, 21))
        self.softwareNameLabel.setStyleSheet("QLabel#softwareNameLabel { background: transparent; color: white; border: none; font-family: Times New Roman; font-size: 20px; font-weight: 600; }")
        self.softwareNameLabel.setObjectName("softwareNameLabel")
        self.minimizeButton = QtWidgets.QPushButton(self.HeaderFrame)
        self.minimizeButton.setGeometry(QtCore.QRect(842, 5, 46, 34))
        self.minimizeButton.setStyleSheet("QPushButton#minimizeButton { background-color: rgba(255,255,255,0.12); color: white; border: 1px solid rgba(255,255,255,0.36); border-radius: 9px; font-size: 18px; } QPushButton#minimizeButton:hover { background-color: rgba(255,255,255,0.24); }")
        self.minimizeButton.setObjectName("minimizeButton")
        self.closeButton = QtWidgets.QPushButton(self.HeaderFrame)
        self.closeButton.setGeometry(QtCore.QRect(900, 5, 46, 34))
        self.closeButton.setStyleSheet("QPushButton#closeButton { background-color: rgba(255,255,255,0.12); color: white; border: 1px solid rgba(255,255,255,0.36); border-radius: 9px; font-size: 18px; } QPushButton#closeButton:hover { background-color: rgba(220,110,130,0.70); }")
        self.closeButton.setObjectName("closeButton")
        self.bodyFrame = QtWidgets.QFrame(self.mainFrame)
        self.bodyFrame.setGeometry(QtCore.QRect(0, 50, 971, 691))
        self.bodyFrame.setStyleSheet("QFrame#bodyFrame { background: rgba(255,255,255,0.16); border-bottom-left-radius: 22px; border-bottom-right-radius: 22px; }")
        self.bodyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bodyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bodyFrame.setObjectName("bodyFrame")
        self.appIconLabel = QtWidgets.QLabel(self.bodyFrame)
        self.appIconLabel.setGeometry(QtCore.QRect(440, 20, 101, 101))
        self.appIconLabel.setStyleSheet("QLabel#appIconLabel { background: qlineargradient(x1:0,y1:0,x2:1,y2:1, stop:0 #8f96d8, stop:1 #b6b2ea); color: white; border: 1px solid rgba(255,255,255,0.75); border-radius: 50px; font-size: 180px; font-weight: 700;}")
        self.appIconLabel.setText("")
        self.appIconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.appIconLabel.setWordWrap(False)
        self.appIconLabel.setObjectName("appIconLabel")
        self.welcomeLabel = QtWidgets.QLabel(self.bodyFrame)
        self.welcomeLabel.setGeometry(QtCore.QRect(220, 123, 570, 58))
        self.welcomeLabel.setStyleSheet("QLabel#welcomeLabel { background: transparent; border: none; color: #505166; font-family: Times New Roman; font-size: 36px; font-weight: 700; }")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.subtitleLabel = QtWidgets.QLabel(self.bodyFrame)
        self.subtitleLabel.setGeometry(QtCore.QRect(255, 183, 500, 62))
        self.subtitleLabel.setStyleSheet("QLabel#subtitleLabel { background: transparent; border: none; color: #777990; font-family: Times New Roman; font-size: 18px; line-height: 140%; }")
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.blockSegmentationCard = QtWidgets.QFrame(self.bodyFrame)
        self.blockSegmentationCard.setGeometry(QtCore.QRect(160, 260, 291, 311))
        self.blockSegmentationCard.setStyleSheet("QFrame#blockSegmentationCard { background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 rgba(255,255,255,0.58), stop:1 rgba(255,255,255,0.30)); border: 1px solid rgba(255,255,255,0.75); border-radius: 22px; } QFrame#blockSegmentationCard:hover { border: 1px solid #9b93df; background: rgba(255,255,255,0.48); }")
        self.blockSegmentationCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.blockSegmentationCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.blockSegmentationCard.setObjectName("blockSegmentationCard")
        self.blockSegiconlabel = QtWidgets.QLabel(self.blockSegmentationCard)
        self.blockSegiconlabel.setGeometry(QtCore.QRect(90, 50, 112, 112))
        self.blockSegiconlabel.setStyleSheet("QLabel#blockSegiconlabel { background: qlineargradient(x1:0,y1:0,x2:1,y2:1, stop:0 #8d7bd9, stop:1 #c4a2ee); border: 1px solid rgba(255,255,255,0.75); border-radius: 26px; color: white; font-family: Segoe UI; font-size: 44px; }")
        self.blockSegiconlabel.setText("")
        self.blockSegiconlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.blockSegiconlabel.setObjectName("blockSegiconlabel")
        self.blockSegtitlelabel = QtWidgets.QLabel(self.blockSegmentationCard)
        self.blockSegtitlelabel.setGeometry(QtCore.QRect(10, 160, 270, 34))
        self.blockSegtitlelabel.setStyleSheet("QLabel#blockSegtitlelabel { background: transparent; border: none; color: #52536a; font-family: Times New Roman; font-size: 23px; font-weight: 700; }")
        self.blockSegtitlelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.blockSegtitlelabel.setObjectName("blockSegtitlelabel")
        self.blockSegdetailslabel = QtWidgets.QLabel(self.blockSegmentationCard)
        self.blockSegdetailslabel.setGeometry(QtCore.QRect(20, 200, 250, 46))
        self.blockSegdetailslabel.setStyleSheet("QLabel#blockSegdetailslabel { background: transparent; border: none; color: #777990; font-family: Times New Roman; font-size: 14px; }")
        self.blockSegdetailslabel.setAlignment(QtCore.Qt.AlignCenter)
        self.blockSegdetailslabel.setWordWrap(True)
        self.blockSegdetailslabel.setObjectName("blockSegdetailslabel")
        self.blockSegOpenButton = QtWidgets.QPushButton(self.blockSegmentationCard)
        self.blockSegOpenButton.setGeometry(QtCore.QRect(20, 250, 250, 42))
        self.blockSegOpenButton.setStyleSheet("QPushButton#blockSegOpenButton { background: qlineargradient(x1:0,y1:0,x2:1,y2:0, stop:0 #8d7bd9, stop:1 #9da0e4); color: white; border: none; border-radius: 20px; font-family: Times New Roman; font-size: 17px; font-weight: 600; } QPushButton#blockSegOpenButton:hover { background: qlineargradient(x1:0,y1:0,x2:1,y2:0, stop:0 #8170cf, stop:1 #9095dc); } QPushButton#blockSegOpenButton:pressed { background: #7467bd; }")
        self.blockSegOpenButton.setObjectName("blockSegOpenButton")
        self.nodeIdentificationCard = QtWidgets.QFrame(self.bodyFrame)
        self.nodeIdentificationCard.setGeometry(QtCore.QRect(520, 260, 301, 311))
        self.nodeIdentificationCard.setStyleSheet("QFrame#nodeIdentificationCard { background: qlineargradient(x1:0,y1:0,x2:0,y2:1, stop:0 rgba(255,255,255,0.58), stop:1 rgba(255,255,255,0.30)); border: 1px solid rgba(255,255,255,0.75); border-radius: 22px; } QFrame#nodeIdentificationCard:hover { border: 1px solid #7db7e8; background: rgba(255,255,255,0.48); }")
        self.nodeIdentificationCard.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nodeIdentificationCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nodeIdentificationCard.setObjectName("nodeIdentificationCard")
        self.nodeIdentiiconlabel = QtWidgets.QLabel(self.nodeIdentificationCard)
        self.nodeIdentiiconlabel.setGeometry(QtCore.QRect(100, 50, 112, 112))
        self.nodeIdentiiconlabel.setStyleSheet("QLabel#nodeIdentiiconlabel { background: qlineargradient(x1:0,y1:0,x2:1,y2:1, stop:0 #6fa6dc, stop:1 #9ecbee); border: 1px solid rgba(255,255,255,0.75); border-radius: 26px; color: white; font-family: Segoe UI; font-size: 44px; }")
        self.nodeIdentiiconlabel.setText("")
        self.nodeIdentiiconlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nodeIdentiiconlabel.setObjectName("nodeIdentiiconlabel")
        self.nodeIdentititlelabel = QtWidgets.QLabel(self.nodeIdentificationCard)
        self.nodeIdentititlelabel.setGeometry(QtCore.QRect(20, 163, 270, 34))
        self.nodeIdentititlelabel.setStyleSheet("QLabel#nodeIdentititlelabel { background: transparent; border: none; color: #52536a; font-family: Times New Roman; font-size: 23px; font-weight: 700; }")
        self.nodeIdentititlelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nodeIdentititlelabel.setObjectName("nodeIdentititlelabel")
        self.nodeIdentidetailslabel = QtWidgets.QLabel(self.nodeIdentificationCard)
        self.nodeIdentidetailslabel.setGeometry(QtCore.QRect(20, 200, 250, 46))
        self.nodeIdentidetailslabel.setStyleSheet("QLabel#nodeIdentidetailslabel { background: transparent; border: none; color: #777990; font-family: Times New Roman; font-size: 14px; }")
        self.nodeIdentidetailslabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nodeIdentidetailslabel.setWordWrap(True)
        self.nodeIdentidetailslabel.setObjectName("nodeIdentidetailslabel")
        self.nodeIdentiOpenButton = QtWidgets.QPushButton(self.nodeIdentificationCard)
        self.nodeIdentiOpenButton.setGeometry(QtCore.QRect(30, 250, 250, 42))
        self.nodeIdentiOpenButton.setStyleSheet("QPushButton#nodeIdentiOpenButton { background: qlineargradient(x1:0,y1:0,x2:1,y2:0, stop:0 #6fa6dc, stop:1 #8fc5ee); color: white; border: none; border-radius: 20px; font-family: Times New Roman; font-size: 17px; font-weight: 600; } QPushButton#nodeIdentiOpenButton:hover { background: qlineargradient(x1:0,y1:0,x2:1,y2:0, stop:0 #629bd3, stop:1 #82b9e8); } QPushButton#nodeIdentiOpenButton:pressed { background: #5b8fc4; }")
        self.nodeIdentiOpenButton.setObjectName("nodeIdentiOpenButton")
        self.infoPanelFrame = QtWidgets.QFrame(self.bodyFrame)
        self.infoPanelFrame.setGeometry(QtCore.QRect(30, 590, 910, 74))
        self.infoPanelFrame.setStyleSheet("QFrame#infoPanelFrame { background: rgba(255,255,255,0.34); border: 1px solid rgba(255,255,255,0.65); border-radius: 20px; }")
        self.infoPanelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoPanelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoPanelFrame.setObjectName("infoPanelFrame")
        self.infoIconLabel = QtWidgets.QLabel(self.infoPanelFrame)
        self.infoIconLabel.setGeometry(QtCore.QRect(26, 17, 40, 40))
        self.infoIconLabel.setStyleSheet("QLabel#infoIconLabel { background: #9da0e4; color: white; border: none; border-radius: 20px; font-family:Times New Roman; font-size: 22px; font-weight: 700; }")
        self.infoIconLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoIconLabel.setObjectName("infoIconLabel")
        self.infoTitleLabel = QtWidgets.QLabel(self.infoPanelFrame)
        self.infoTitleLabel.setGeometry(QtCore.QRect(82, 12, 520, 26))
        self.infoTitleLabel.setStyleSheet("QLabel#infoTitleLabel { background: transparent; border: none; color: #5f6172; font-family: Times New Roman; font-size: 16px; font-weight: 600; }")
        self.infoTitleLabel.setObjectName("infoTitleLabel")
        self.infoDetailsLabel = QtWidgets.QLabel(self.infoPanelFrame)
        self.infoDetailsLabel.setGeometry(QtCore.QRect(82, 38, 560, 24))
        self.infoDetailsLabel.setStyleSheet("QLabel#infoDetailsLabel { background: transparent; border: none; color: #7b7d94; font-family: Times New Roman; font-size: 13px; }")
        self.infoDetailsLabel.setObjectName("infoDetailsLabel")
        self.label = QtWidgets.QLabel(self.infoPanelFrame)
        self.label.setGeometry(QtCore.QRect(760, 20, 131, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.mainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AI Software"))
        self.softwareNameLabel.setText(_translate("MainWindow", "AI Software"))
        self.minimizeButton.setText(_translate("MainWindow", "−"))
        self.closeButton.setText(_translate("MainWindow", "×"))
        self.welcomeLabel.setText(_translate("MainWindow", "Welcome to AI Software"))
        self.subtitleLabel.setText(_translate("MainWindow", "Advanced IC analysis powered by AI.\n"
"Choose an analysis mode to get started."))
        self.blockSegtitlelabel.setText(_translate("MainWindow", "Block Segmentation"))
        self.blockSegdetailslabel.setText(_translate("MainWindow", "Segment IC images into functional blocks and calculate area of each block."))
        self.blockSegOpenButton.setText(_translate("MainWindow", "Open  →"))
        self.nodeIdentititlelabel.setText(_translate("MainWindow", "Node Identification"))
        self.nodeIdentidetailslabel.setText(_translate("MainWindow", "Detect and identify nodes in IC images for detailed structure-level analysis."))
        self.nodeIdentiOpenButton.setText(_translate("MainWindow", "Open  →"))
        self.infoIconLabel.setText(_translate("MainWindow", "i"))
        self.infoTitleLabel.setText(_translate("MainWindow", "Select an analysis mode to begin."))
        self.infoDetailsLabel.setText(_translate("MainWindow", "Upload IC teardown images and let the AI extract block-level or node-level insights."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
