# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\project_Files\ai_Node_identification\UI\dot_UI_files\node_Analysis_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 782)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #eaf4fd;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget {\n"
"    background: transparent;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setStyleSheet("QFrame#mainFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #eef7fe,\n"
"        stop:1 #d7eaf9\n"
"    );\n"
"    border: 1px solid rgba(255,255,255,0.70);\n"
"    border-radius: 24px;\n"
"}")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.HeaderFrame = QtWidgets.QFrame(self.mainFrame)
        self.HeaderFrame.setGeometry(QtCore.QRect(20, 10, 561, 31))
        self.HeaderFrame.setStyleSheet("QFrame#HeaderFrame {\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.HeaderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HeaderFrame.setObjectName("HeaderFrame")
        self.softwareNameLabel = QtWidgets.QLabel(self.HeaderFrame)
        self.softwareNameLabel.setGeometry(QtCore.QRect(0, 0, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.softwareNameLabel.setFont(font)
        self.softwareNameLabel.setStyleSheet("QLabel#softwareNameLabel {\n"
"    background: transparent;\n"
"    color: #1c4fa3;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"    border: none;\n"
"    padding-left: 6px;\n"
"}")
        self.softwareNameLabel.setObjectName("softwareNameLabel")
        self.Image_showing_frame = QtWidgets.QFrame(self.mainFrame)
        self.Image_showing_frame.setGeometry(QtCore.QRect(-10, 40, 901, 431))
        self.Image_showing_frame.setStyleSheet("QFrame#Image_showing_frame {\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.Image_showing_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Image_showing_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Image_showing_frame.setObjectName("Image_showing_frame")
        self.originalImageframe = QtWidgets.QFrame(self.Image_showing_frame)
        self.originalImageframe.setGeometry(QtCore.QRect(20, 10, 871, 421))
        self.originalImageframe.setStyleSheet("QFrame#originalImageframe {\n"
"    background: rgba(255,255,255,0.36);\n"
"    border: 1px solid rgba(111, 174, 245, 0.55);\n"
"    border-radius: 18px;\n"
"}")
        self.originalImageframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.originalImageframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.originalImageframe.setObjectName("originalImageframe")
        self.identifiedLineLeft = QtWidgets.QFrame(self.originalImageframe)
        self.identifiedLineLeft.setGeometry(QtCore.QRect(210, 400, 115, 2))
        self.identifiedLineLeft.setStyleSheet("QFrame#identifiedLineLeft, QFrame#identifiedLineRight {\n"
"    background: #9fc9f8;\n"
"    border: none;\n"
"}")
        self.identifiedLineLeft.setObjectName("identifiedLineLeft")
        self.identifiedGlowDotLeft = QtWidgets.QLabel(self.originalImageframe)
        self.identifiedGlowDotLeft.setGeometry(QtCore.QRect(330, 394, 12, 12))
        self.identifiedGlowDotLeft.setStyleSheet("QLabel#identifiedGlowDotLeft, QLabel#identifiedGlowDotRight {\n"
"    background: #247ef4;\n"
"    border-radius: 6px;\n"
"}")
        self.identifiedGlowDotLeft.setText("")
        self.identifiedGlowDotLeft.setObjectName("identifiedGlowDotLeft")
        self.originalImagelabel = QtWidgets.QLabel(self.originalImageframe)
        self.originalImagelabel.setGeometry(QtCore.QRect(352, 386, 170, 24))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.originalImagelabel.setFont(font)
        self.originalImagelabel.setStyleSheet("QLabel#originalImagelabel {\n"
"    color: #1e6de8;\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.originalImagelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.originalImagelabel.setObjectName("originalImagelabel")
        self.identifiedGlowDotRight = QtWidgets.QLabel(self.originalImageframe)
        self.identifiedGlowDotRight.setGeometry(QtCore.QRect(530, 394, 12, 12))
        self.identifiedGlowDotRight.setStyleSheet("QLabel#identifiedGlowDotLeft, QLabel#identifiedGlowDotRight {\n"
"    background: #247ef4;\n"
"    border-radius: 6px;\n"
"}")
        self.identifiedGlowDotRight.setText("")
        self.identifiedGlowDotRight.setObjectName("identifiedGlowDotRight")
        self.identifiedLineRight = QtWidgets.QFrame(self.originalImageframe)
        self.identifiedLineRight.setGeometry(QtCore.QRect(546, 400, 115, 2))
        self.identifiedLineRight.setStyleSheet("QFrame#identifiedLineLeft, QFrame#identifiedLineRight {\n"
"    background: #9fc9f8;\n"
"    border: none;\n"
"}")
        self.identifiedLineRight.setObjectName("identifiedLineRight")
        self.identifiedImageframe = QtWidgets.QFrame(self.originalImageframe)
        self.identifiedImageframe.setGeometry(QtCore.QRect(10, 10, 851, 371))
        self.identifiedImageframe.setStyleSheet("QFrame#identifiedImageframe {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #1e4f96,\n"
"        stop:0.5 #255dae,\n"
"        stop:1 #173e78\n"
"    );\n"
"    border: 1px solid #6faef5;\n"
"    border-radius: 16px;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    font-weight: 600;\n"
"}")
        self.identifiedImageframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.identifiedImageframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.identifiedImageframe.setObjectName("identifiedImageframe")
        self.showDetailsframe = QtWidgets.QFrame(self.mainFrame)
        self.showDetailsframe.setGeometry(QtCore.QRect(10, 480, 871, 211))
        self.showDetailsframe.setStyleSheet("QFrame#showDetailsframe {\n"
"    background: rgba(255,255,255,0.32);\n"
"    border: 1px solid rgba(111, 174, 245, 0.45);\n"
"    border-radius: 16px;\n"
"}")
        self.showDetailsframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.showDetailsframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.showDetailsframe.setObjectName("showDetailsframe")
        self.analysisLabel = QtWidgets.QLabel(self.showDetailsframe)
        self.analysisLabel.setGeometry(QtCore.QRect(13, 8, 841, 36))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.analysisLabel.setFont(font)
        self.analysisLabel.setStyleSheet("QLabel#analysisLabel {\n"
"    color: #173a84;\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"    border-bottom: 2px solid #d6e7fb;\n"
"    padding-bottom: 4px;\n"
"}")
        self.analysisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisLabel.setObjectName("analysisLabel")
        self.tickLabel = QtWidgets.QLabel(self.showDetailsframe)
        self.tickLabel.setGeometry(QtCore.QRect(400, 50, 64, 64))
        self.tickLabel.setStyleSheet("QLabel#tickLabel {\n"
"    background: rgba(255,255,255,0.70);\n"
"    border: 2px solid #7bb8f6;\n"
"    border-radius: 32px;\n"
"    color: #1d6be6;\n"
"    font-size: 28px;\n"
"    font-weight: 700;\n"
"}")
        self.tickLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tickLabel.setObjectName("tickLabel")
        self.resultMainLabel = QtWidgets.QLabel(self.showDetailsframe)
        self.resultMainLabel.setGeometry(QtCore.QRect(215, 90, 440, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.resultMainLabel.setFont(font)
        self.resultMainLabel.setStyleSheet("QLabel#resultMainLabel {\n"
"    background: transparent;\n"
"    color: #0c57cf;\n"
"    border: none;\n"
"}")
        self.resultMainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultMainLabel.setObjectName("resultMainLabel")
        self.resultSubLabel = QtWidgets.QLabel(self.showDetailsframe)
        self.resultSubLabel.setGeometry(QtCore.QRect(300, 180, 270, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.resultSubLabel.setFont(font)
        self.resultSubLabel.setStyleSheet("QLabel#resultSubLabel {\n"
"    background: transparent;\n"
"    color: #0c57cf;\n"
"    border: none;\n"
"}")
        self.resultSubLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultSubLabel.setObjectName("resultSubLabel")
        self.closePushbutton = QtWidgets.QPushButton(self.mainFrame)
        self.closePushbutton.setGeometry(QtCore.QRect(460, 700, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.closePushbutton.setFont(font)
        self.closePushbutton.setStyleSheet("QPushButton#closePushbutton {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #0c78ff,\n"
"        stop:1 #0059d9\n"
"    );\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton#closePushbutton:hover {\n"
"    background: qlineargradient(\n"
"        x1:1, y1:1, x2:0, y2:1,\n"
"        stop:0 #2587ff,\n"
"        stop:1 #0b67e7\n"
"    );\n"
"}")
        self.closePushbutton.setObjectName("closePushbutton")
        self.detailsPushbutton = QtWidgets.QPushButton(self.mainFrame)
        self.detailsPushbutton.setGeometry(QtCore.QRect(140, 700, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.detailsPushbutton.setFont(font)
        self.detailsPushbutton.setStyleSheet("QPushButton#detailsPushbutton {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #0059d9,\n"
"        stop:1 #0c78ff\n"
"    );\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton#detailsPushbutton:hover {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #2587ff,\n"
"        stop:1 #0b67e7\n"
"    );\n"
"}")
        self.detailsPushbutton.setObjectName("detailsPushbutton")
        self.gridLayout.addWidget(self.mainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.softwareNameLabel.setText(_translate("MainWindow", "Node Classification"))
        self.originalImagelabel.setText(_translate("MainWindow", "Identified Area"))
        self.analysisLabel.setText(_translate("MainWindow", "Classified Node Type"))
        self.tickLabel.setText(_translate("MainWindow", "✓"))
        self.resultMainLabel.setText(_translate("MainWindow", "FinFET"))
        self.resultSubLabel.setText(_translate("MainWindow", "Technology Class"))
        self.closePushbutton.setText(_translate("MainWindow", "Close"))
        self.detailsPushbutton.setText(_translate("MainWindow", "Details"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
